version: 2.1

jobs:
  build:
    # docker:
    #   - image: ubuntu
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      # - run: apt update
      # - run: apt install -y build-essential curl
      - run: 
          no_output_timeout: 120m
          command: ./build-ffmpeg --build
          environment:
            NUMJOBS:
              8
      - save_cache:
          key: build-cache
          paths:
            - ffmpeg/
  publish: 
    docker:
      - image: ubuntu
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache
      - run: ls ffmpeg/


workflows:
  build:
    jobs:
      - build
      - publish:
          requires:
            - build