version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt install build-essential curl
      - run: ./build-ffmpeg --build

workflows:
  build_and_test:
    jobs:
      - build