version: 2.1

jobs:
  build_macos:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: mkdir -p workspace/artifacts/
      - run: touch workspace/artifacts/test.test
      # - run: 
      #     no_output_timeout: 120m
      #     command: ./build-ffmpeg --build
      #     environment:
      #       NUMJOBS:
      #         8

      - persist_to_workspace:
          root: workspace/artifacts

  build_linux:
    # docker:
    #   - image: ubuntu
    # steps:
    #   - checkout
    #   - run: apt update
    #   - run: apt install -y build-essential curl
    #   - run: 
    #       no_output_timeout: 120m
    #       command: ./build-ffmpeg --build
    #       environment:
    #         NUMJOBS:
    #           8
    #   - save_cache:
    #       key: build-cache
    #       paths:
    #         - ffmpeg/

  publish: 
    docker:
      - image: ubuntu
    steps:
      - attach_workspace:
          at: workspace/artifacts
      - run: ls workspace/artifacts
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
      - run: tar -xf ghr_v0.16.0_linux_amd64.tar.gz
      - run: ./ghr_v0.16.0_linux_amd64/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete version1 ./workspace/artifacts/ 


workflows:
  build:
    jobs:
      - build_macos
      # - build_linux
      - publish:
          requires:
            - build_macos
            # - build_linux