version: 2.1

jobs:
  build_macos:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - workspace-cache
            - packages-cache
      - run: mkdir -p ~/project/workspace/$ARTIFACT_NAME
      - run: 
          no_output_timeout: 120m
          command: ./build-ffmpeg --build
          environment:
            NUMJOBS:
              8
            ARTIFACT_NAME:
              ffmpeg_macos
      - save_cache:
          key: packages-cache
          paths:
            - ~/project/packages/
      - save_cache:
          key: workspace-cache
          paths:
            - ~/project/workspace/
      - persist_to_workspace:
          root: ~/project/
          paths:
            - workspace/$ARTIFACT_NAME

  build_linux:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt update
      - run: apt install -y build-essential curl
      - run: 
          no_output_timeout: 120m
          command: ./build-ffmpeg --build
          environment:
            NUMJOBS:
              8

  publish: 
    docker:
      - image: ubuntu
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir /root/artifacts
      - run: |
            directory=/root/workspace
            for subdir in "$directory"/*; do
              if [ -d "$subdir" ]; then  
                subdir_name="$(basename "$subdir")"
                tar -czvf "$subdir_name.tar.gz" -C "$directory" "$subdir_name"
                mv "$subdir_name.tar.gz" /root/artifacts
              fi
            done
      - run: apt update
      - run: cd /root/
      - run: apt install -y wget
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
      - run: tar -xf ghr_v0.16.0_linux_amd64.tar.gz
      - run: 
          command: ./ghr_v0.16.0_linux_amd64/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /root/artifacts/ 
          environment:
            VERSION:
              version1

workflows:
  build:
    jobs:
      - build_macos
      - build_linux
      - publish:
          requires:
            - build_macos
            # - build_linux