version: 2.1

jobs:
  build_macos:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: mkdir -p workspace/ffmpeg_macos
      - run: echo "hello" > workspace/ffmpeg_macos/test.test
      # - run: 
      #     no_output_timeout: 120m
      #     command: ./build-ffmpeg --build
      #     environment:
      #       NUMJOBS:
      #         8
      #       ARTIFACT_NAME:
      #         ffmpeg_macos

      - persist_to_workspace:
          root: ~/project/
          paths:
            - workspace/ffmpeg_macos

  # build_linux:
    # docker:
    #   - image: ubuntu
    # steps:
    #   - checkout
    #   - run: apt update
    #   - run: apt install -y build-essential curl
    #   - run: 
    #       no_output_timeout: 120m
    #       command: ./build-ffmpeg --build
    #       environment:
    #         NUMJOBS:
    #           8
    #   - save_cache:
    #       key: build-cache
    #       paths:
    #         - ffmpeg/

  publish: 
    docker:
      - image: ubuntu
    steps:
      - attach_workspace:
          at: ~/
      - run: apt update
      - run: apt install -y wget
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
      - run: tar -xf ghr_v0.16.0_linux_amd64.tar.gz
      #- run: for each file in ~/workspace -> tar file, cp file.tar to ~/artifacts
      - run: |
            for d in */ ; do
              tar -czvf "$d.tar.gz" "~/workspace/$d"
              cp "$d.tar.gz" ~/artifacts
            done
      - run: 
          command: ./ghr_v0.16.0_linux_amd64/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/artifacts/ 
          environment:
            VERSION:
              version1

workflows:
  build:
    jobs:
      - build_macos
      # - build_linux
      - publish:
          requires:
            - build_macos
            # - build_linux